import type { Metadata } from "next";
import "./globals.css";
import { Outfit, Space_Grotesk } from "next/font/google";
import FlashlightBackground from "@/components/flashlight-background";

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-space-grotesk",
  weight: [
    "300", // font-light
    "400", // font-normal
    "500", // font-medium
    "600", // font-semibold
    "700", // font-bold
  ],
});

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
  weight: [
    "100", // font-thin
    "200", // font-extralight
    "300", // font-light
    "400", // font-normal
    "500", // font-medium
    "600", // font-semibold
    "700", // font-bold
    "800", // font-extrabold
    "900", // font-black
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen bg-[url('/background-test.png')] bg-cover bg-center bg-no-repeat md:bg-fixed ${spaceGrotesk.className} ${outfit.className}`}>
        <FlashlightBackground>
          {children}
        </FlashlightBackground>
      </body>
    </html>
  );
}
